-- vim.g.python3_host_prog = vim.fn.expand("~/.pyenv/versions/3.9.5/bin/python")
-- vim.g.python_host_prog = vim.fn.expand("~/.pyenv/versions/2.7.18/bin/python")
-- vim.g.node_host_prog = vim.fn.expand("~/.nvm/versions/node/v17.0.1/bin/node")
